### ISSUE TITLE
Cell Balancing 

### ISSUE THREAD

**Issue by B-hafedh** [LibreSolar/bms-c1#32]
Do you think that internal cell balancing with I_Balance ~= 65 mA is sufficient for most applications, and why ??
what about power dissipation and the resulting heat ?

**Comment by martinjaeger** [comment]
The resulting heat is not really an issue, but 65 mA may not be enough for applications with very large cells or cells with very inhomogeneous capacity or self discharge rate.

As always, it's a tradeoff between amount of functions/applications and cost. Active balancing costs **much** more than this rather simple passive balancing. That's why it was discarded for this BMS development targeting very cost-sensitive energy access applications.
