### ISSUE TITLE
BMS-C1: Kicad Library

### ISSUE THREAD

**Issue by joshuasiumao** [LibreSolar/bms-c1#38]
Where can I find Kicad's library for those symbols, footprints,  and 3D files?

**Comment by martinjaeger** [comment]
The symbol library is here: https://github.com/LibreSolar/kicad-symbols

Normally it should also work without the correct library path, as KiCad stores the symbol inside the schematic since v6.0.

Unfortunately I cannot publish the 3D files as they were partly downloaded from companies like Würth and they don't have an open license.
