### ISSUE TITLE
Fix NPTH clearance in v0.4

### ISSUE THREAD

**Issue by devbotas** [LibreSolar/bms-c1#55]
aisler.net complains about this:
![image](https://github.com/LibreSolar/bms-c1/assets/71982803/f0c68ae5-93b5-45c6-b28d-d9368fed4fc9)

And indeed, one of those USB connector holes got electroplated, shorting 3V3 to GND. 

I (hopefully) fixed my PCBs by drilling a slightly larger hole.

**Comment by martinjaeger** [comment]
Thanks a lot for reporting this issue.

I had ordered one PCB for validating the design, which worked fine. However, the NPTH of the USB connector looks indeed wrong. Also the KiCAD DRC didn't complain about this. That's very annoying, as I have already ordered a batch of assembled boards.

Will fix the issue and keep you updated.

**Comment by martinjaeger** [comment]
The good news is: I could stop the assembly just before placement of the parts. I will get the PCBs for double-checking. Most probably we will have to re-order them.

@devbotas Your bug report came just in time. Thanks again! If you like, I can send you a fully assembled v0.3.3 board for free, so that you can immediately start working with the BMS. Please send me an email (martin at libre solar) with contact details.

**Comment by devbotas** [comment]
Great to hear! Although your PCBs may still be OK.  The electrical test of my first batch was fine (or maybe they didn't do it, I don't know), but it was lost in shipping. It is the second batch that resulted in faulty tests.

**Comment by martinjaeger** [comment]
@devbotas FYI: I tested the insulation resistance of approx. 20 of the v0.4.0 boards with a Fluke 1507 and got >11 GOhm (max. of measurement range) for all of them for a test voltage of 1000 V. Looks like these PCBs were fine. However, the clearance should still be fixed, of course.

Please see the PR linked above for the fix.

**Comment by devbotas** [comment]
So you've got lucky, nice 👍
